name = "simple-api-example"
main = "index.ts"
compatibility_date = "2024-12-30"

[durable_objects]
bindings = [
  { name = "DOFull", class_name = "SimpleAPI" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SimpleAPI"]
